import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import assert from "node:assert";
const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, "..", "index.html"), "utf-8");
const m = html.match(/<script>([\s\S]*?)<\/script>/);
assert.ok(m, "index.html 中应包含 <script> 块");
const moduleShim = { exports: {} };
new Function("module","exports",m[1])(moduleShim, moduleShim.exports);
const { hashTextToVec, parseInput, euclid, kmeans } = moduleShim.exports;
const v1 = hashTextToVec("苹果");
assert.deepStrictEqual(v1, hashTextToVec("苹果"));
assert.ok(v1[0] >= -1 && v1[0] <= 1);
assert.notDeepStrictEqual(hashTextToVec("苹果"), hashTextToVec("香蕉"));
const pts = parseInput("苹果 1.2 0.5\n香蕉 -0.8 0.3\n汽车");
assert.strictEqual(pts.length, 3);
assert.strictEqual(pts[0].x, 1.2);
assert.ok(pts[2].hashed);
assert.ok(Math.abs(euclid([0,0],[3,4]) - 5) < 1e-9);
const clusterA = [{x:0,y:0},{x:0.2,y:0.1},{x:-0.1,y:0.1}];
const clusterB = [{x:5,y:5},{x:5.2,y:5.1},{x:4.9,y:5.2}];
const labels = kmeans([...clusterA, ...clusterB], 2);
assert.strictEqual(labels.length, 6);
assert.strictEqual(labels[0], labels[1]);
assert.strictEqual(labels[3], labels[4]);
assert.notStrictEqual(labels[0], labels[3]);
assert.deepStrictEqual(kmeans([], 3), []);
console.log("✓ embedding-plot-web 全部 Node 断言通过");
